name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or 'master' if your repo uses that

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👇 Step 1: Set up Java for Maven
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 👇 Step 2: Install Maven and build WAR
      - name: Build WAR using Maven
        run: mvn clean package -DskipTests

      # 👇 Step 3: Set up Docker builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 👇 Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 👇 Step 5: Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rudreshrudra1924:latest
